### ISSUE TITLE
De link naar Speed Dial 2 wijst naar TamperMonkey

### ISSUE THREAD

**Issue by GeneralSan** [guyvdn/Toolbelt#1]
In document https://github.com/guyvdn/Toolbelt/tree/main/BrowserExtensions vind je een link met de tekst "Speed Dial 2 New Tab", maar die wijst naar TamperMonkey. De juiste link is  vermoedelijk https://chrome.google.com/webstore/detail/speed-dial-2-new-tab/jpfpebmajhhopeonhlcgidhclcccjcik

**Comment by guyvdn** [comment]
Bedankt om het te melden @GeneralSan ik heb het aangepast.
